services:
  echo-tts-api:
    build: .
    ports:
      - "8004:8004"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ "1" ]
              capabilities: [gpu]
    volumes:
      - "./audio_prompts:/app/audio_prompts"
      - "./cache/huggingface:/root/.cache/huggingface"
    runtime: nvidia
    restart: unless-stopped

